env:
  browser: true
  es6: true
extends:
  - 'plugin:react/recommended'
  - airbnb
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
rules:
  {
    'react/jsx-props-no-spreading': 'off',
    'object-curly-newline': 'off',
    'react/prop-types': 0,
    'no-unused-vars': 0,
    'react/jsx-filename-extension': [2, { 'extensions': ['.js', '.jsx', '.ts', '.tsx'] }],
    'import/no-extraneous-dependencies': [2, { devDependencies: ['**/test.tsx', '**/test.ts'] }],
    'import/extensions':
      ['error', 'ignorePackages', { 'js': 'never', 'jsx': 'never', 'ts': 'never', 'tsx': 'never' }],
    'comma-dangle':
      [
        'error',
        {
          arrays: 'never',
          exports: 'never',
          functions: 'never',
          imports: 'never',
          objects: 'never',
        },
      ],
    'no-param-reassign': ['error', { props: true, ignorePropertyModificationsFor: ['state'] }],
  }
settings:
  {
    'import/resolver':
      { 'node': { 'paths': ['src'], 'extensions': ['.js', '.jsx', '.ts', '.tsx'] } },
  }
